apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev-apps
  name: dev-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name:  dev-api
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dev-api
    spec:
      containers:
      - name:  dev-api
        image: 850995548837.dkr.ecr.ap-south-1.amazonaws.com/dev_backend_api:8188127a62ff0b513b72279face7ba7e23589a3f
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_NAMES
          value: "backend/env"